language: ruby
cache: bundler
services:
- postgresql
before_script:
- bin/rails db:create
script:
- bundle exec rubocop --require rubocop-rails
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: REGENERATE_API_KEY
  run: "bin/rails db:migrate"
